### ISSUE TITLE
Deprecated unit measure

### ISSUE THREAD

**Issue by ribanez7** [michalmuskala/plug_attack#16]
Hi Michal,

There's a warning from plug_attack:

> warning: deprecated time unit: :milliseconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
>   (plug_attack) lib/storage/ets.ex:115: PlugAttack.Storage.Ets.do_clean/1
>   (plug_attack) lib/storage/ets.ex:109: PlugAttack.Storage.Ets.handle_info/2
>   (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
>   (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
>   (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

**Comment by michalmuskala** [comment]
This was fixed in `0.4.0`, an update should solve the issue.
